ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_provider_fk
ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_patient_fk
ALTER TABLE DRUGTREATMENT DROP CONSTRAINT FK_DRUGTREATMENT_ID
ALTER TABLE RADIOLOGYTREATMENT DROP CONSTRAINT FK_RADIOLOGYTREATMENT_ID
ALTER TABLE SURGERY DROP CONSTRAINT FK_SURGERY_ID
ALTER TABLE RADIOLOGYDATES DROP CONSTRAINT FK_RADIOLOGYDATES_radiologyTreatment_fk
DROP TABLE PATIENT CASCADE
DROP TABLE TREATMENT CASCADE
DROP TABLE DRUGTREATMENT CASCADE
DROP TABLE RADIOLOGYTREATMENT CASCADE
DROP TABLE SURGERY CASCADE
DROP TABLE PROVIDER CASCADE
DROP TABLE RADIOLOGYDATES CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
