//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.16 at 03:45:40 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.example.org/clinic/schemas/treatment", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.stevens.cs548.clinic.service.dto.util;
